name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Adapt paths for GitHub Pages
      run: |
        # Leer configuración del repositorio
        REPO_NAME=$(cat public/github-config.json | grep -o '"baseUrl": "[^"]*"' | cut -d'"' -f4 | sed 's|/||g')
        
        # Actualizar rutas en index.html
        sed -i "s|href=\"/|href=\"/$REPO_NAME/|g" dist/index.html
        sed -i "s|src=\"/|src=\"/$REPO_NAME/|g" dist/index.html
        
        # Actualizar manifest.webmanifest
        if [ -f dist/manifest.webmanifest ]; then
          sed -i "s|\"start_url\":\"/\"|\"start_url\":\"/$REPO_NAME/\"|g" dist/manifest.webmanifest
          sed -i "s|\"scope\":\"/\"|\"scope\":\"/$REPO_NAME/\"|g" dist/manifest.webmanifest
        fi
        
        # Actualizar service worker si existe
        if [ -f dist/sw.js ]; then
          sed -i "s|self.location.origin|self.location.origin + '/$REPO_NAME'|g" dist/sw.js
        fi
      
    - name: Create .nojekyll
      run: touch dist/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4